### ISSUE TITLE
Python OSError: Invalid cross-device link

### ISSUE THREAD

**Issue by mpsijm** [Kattis/problemtools#107]
Running the `problem2pdf` tool from the Docker version fails when the result PDF should be outputted across the container's file system boundaries..

Example: In my current working directory on the host, I have a problem in the Kattis Problem Format.
Then, I run `problem2pdf` like this, mounting my current working directory under `/mnt` and calling `problem2pdf` on this directory:
```bash
docker run --rm -it -v $(pwd):/mnt problemtools/icpc problem2pdf /mnt
```
Since no output file is specified with `-o`, it will write to `/` by default, but adding e.g. `-o /tmp/problem.pdf` will also trigger the error.

This is the error that is shown when running above command:
```
(...long TeX log...)
Output written on tmp5GuO3F.pdf (1 page, 117608 bytes).
Transcript written on tmp5GuO3F.log.
Traceback (most recent call last):
  File "/usr/bin/problem2pdf", line 11, in <module>
    load_entry_point('problemtools==1.20181111', 'console_scripts', 'problem2pdf')()
  File "/usr/lib/python2.7/dist-packages/problemtools/problem2pdf.py", line 91, in main
    convert(texfile, options)
  File "/usr/lib/python2.7/dist-packages/problemtools/problem2pdf.py", line 46, in convert
    os.rename(os.path.splitext(texfile)[0] + '.pdf', destfile)
OSError: [Errno 18] Invalid cross-device link
```

Apparently, [this line](https://github.com/Kattis/problemtools/blob/master/problemtools/problem2pdf.py#L46) fails because `os.rename` cannot move a file across file system boundaries (see also [this SO post](https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link)).

Note that this error does not appear when passing `-o /mnt/problem.pdf`, because in that case apparently no file system boundaries are crossed when renaming the PDF.

**Comment by austrin** [comment]
Fixed in `develop` branch.
