### ISSUE TITLE
Display output for failing input validators

### ISSUE THREAD

**Issue by simonlindholm** [Kattis/problemtools#109]
When an input validator fails on a file, it would be useful to see its stdout/stderr/return code to debug the failure.

I know @austrin has thought about doing this; just filing to have a tracking issue. I think this is fairly important, actually, because right now it's rather hard to debug such failures if you don't have anyone around who knows problemtools intimately. `checktestdata` is hard to know how to invoke, and input validator flags also complicate things.

**Comment by austrin** [comment]
Indirectly related progress: verifyproblem now does this for *output* validators.  Baby steps.

**Comment by austrin** [comment]
This is now fixed.
