### ISSUE TITLE
make builddeb fails in a clean repository clone

### ISSUE THREAD

**Issue by lukipuki** [Kattis/problemtools#11]
* Make a clean repository clone
* Run `make builddeb`
* It fails with
```
make[2]: Entering directory `/home/lukas/code/problemtools'
cd support/checktestdata && ./bootstrap
/bin/sh: 1: ./bootstrap: not found
```

`git submodule update --init --recursive` fixes the problem.

I think that either the `make builddeb` command should fetch the submodule or an extra step should be explicitely stated in the instructions in README.md.

**Comment by austrin** [comment]
Fixed (make now fetches the submodule).
