### ISSUE TITLE
Not able to install with the given command

### ISSUE THREAD

**Issue by LarsAstrom** [Kattis/problemtools#111]
I tried installing on Ubuntu with command 

pip install git+https://github.com/kattis/problemtools

Got the following, what to do?

![screenshot from 2018-12-28 19-54-53](https://user-images.githubusercontent.com/38130731/50525285-cf628780-0ada-11e9-9b75-632fd6f42c2f.png)

**Comment by austrin** [comment]
Indeed.  I've now fixed this so that pip will give a more informative error message if you try to install it under Python 3.  (At least if you run pip version 9 or higher).

Will open an issue about supporting mixed 2/3.
