### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by austrin** [Kattis/problemtools#116]
It would be nice to be able to run problemtools in Python 3 and not require Python 2.

The main obstacle is probably that the Plastex library does not support Python 3, but since this is only used for html conversion, one can imagine making it so that the other parts of problemtools still run on Python 3.

**Comment by simonlindholm** [comment]
Plastex supports Python 3 since about a year ago IIRC.

**Comment by austrin** [comment]
Ah, that's nice.  One small snag to be aware of here is that the plastex version that is debian-packaged is severely behind (more than 5 years old).

Maybe it is fine to say that if you want to run problemtools under python 3 then you need to install plastex through pip to get a sufficiently recent version.  But this could also be a big can of worms, in that it is possible that problemtools doesn't work correctly with a recent plastex version, since this hasn't been tested (as far as I know) and problemtools does contain some hacks to work around various issues in plastex.

**Comment by austrin** [comment]
Once #147 is merged I consider this fixed.  As far as I am aware problemtools now works with Python 3 (though there may of course be some bugs or things that I have missed testing).
