### ISSUE TITLE
Git installation failure in both windows and linux (failed with error code 1)

### ISSUE THREAD

**Issue by jeffreycordero** [Kattis/problemtools#118]
I have attempted to install from multiple computers, including windows 10 and ubuntu. Each time I get this error:

"Command "C:\Python27\python2.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jeffr\\appdata\\local\\temp\\pip-kuly7s-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jeffr\appdata\local\temp\pip-akh9mb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jeffr\appdata\local\temp\pip-kuly7s-build\"

Full Installation Output:
"Cache entry deserialization failed, entry ignored
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 509kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-19.0.3
PS C:\> python2 -m pip install git+https://github.com/kattis/problemtools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/kattis/problemtools
  Cloning https://github.com/kattis/problemtools to c:\users\jeffr\appdata\local\temp\pip-req-build-_u50f2
Requirement already satisfied: PyYAML in c:\python27\lib\site-packages (from problemtools==1.20190222) (3.13)
Requirement already satisfied: plasTeX in c:\python27\lib\site-packages (from problemtools==1.20190222) (1.0)
Installing collected packages: problemtools
  Running setup.py install for problemtools ... error
    Complete output from command C:\Python27\python2.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jeffr\\appdata\\local\\temp\\pip-req-build-_u50f2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jeffr\appdata\local\temp\pip-record-hzz0m4\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_support
    Running command: make -C support install DESTDIR=c:\users\jeffr\appdata\local\temp\pip-req-build-_u50f2\build\lib\problemtools\support
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Python27\python2.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jeffr\\appdata\\local\\temp\\pip-req-build-_u50f2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jeffr\appdata\local\temp\pip-record-hzz0m4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jeffr\appdata\local\temp\pip-req-build-_u50f2\"

**Comment by austrin** [comment]
@jeffreycordero Windows is unfortunately not supported, other than running through Docker as described here: https://github.com/kattis/problemtools#method-2-use-docker

Can you post the error you get on Linux instead?  If the error you get there says more or less the same thing, my guess is that you don't have all the dependencies installed on your system (as described here: https://github.com/kattis/problemtools#requirements-and-compatibility ).

**Comment by jeffreycordero** [comment]
I didn't realize it was Debian Linux, that worked correctly.
