### ISSUE TITLE
Formatting sample interactions for interactive problems

### ISSUE THREAD

**Issue by masonsbro** [Kattis/problemtools#123]
I'm writing an interactive problem, and my sample .in and .ans files don't correspond to actual input and output of any real submission/interaction. I would like to use a different .in and .ans for displaying in the problem statement than for judging. Is this possible, or should I just write my own description of a sample run?

**Comment by ghamerly** [comment]
Typically an interactive problem has no sample input/output. Rather, it has a description of the interaction, such as https://open.kattis.com/problems/communicatingstrategy 

Problemtools has in-development support for showing this using .interaction files. See this branch: https://github.com/Kattis/problemtools/commits/interactive-samples

**Comment by masonsbro** [comment]
Thanks. For now I'll use a format like the one in Communicating The Strategy.
