### ISSUE TITLE
Check output_validators with random garbage as input

### ISSUE THREAD

**Issue by niemela** [Kattis/problemtools#13]
Most cases of bad output validators that we've had so far would probably have been caught if `verifyproblem` simply ran the output validator with random junk as submission output.
If this causes validator to violate protocol (e.g. by crashing) then that's an error of course.
If the validator accepts the random junk, a warning should be issued (similarly to what is done if input validator accepts random junk).

**Comment by austrin** [comment]
Fixed in 9e96e37.
