### ISSUE TITLE
verifyproblem.py crashes on time limit warning

### ISSUE THREAD

**Issue by evouga** [Kattis/problemtools#131]
I get the following error when a TLE solution triggers a "sensitive to time limit" warning:

>   File "/u/evouga/icpc/problemtools/problemtools/verifyproblem.py", line 1272, in check_submission
    r1, r2 = result1, result2 if result1.verdict == result2.verdict else result1.verdict, result2.verdict
ValueError: too many values to unpack

I'm no Python expert but I believe there is a precedence problem with line 1272 of verifyproblem.py. I fixed the error locally with this change:

````
            r1, r2 = (result1, result2) if result1.verdict == result2.verdict else (result1.verdict, result2.verdict)
````

**Comment by ghamerly** [comment]
Thanks! I think you're right; I can replicate this behavior like this:
```
a, b = 1, 2 if 3 == 4 else 4, 5    # crashes
a, b = (1, 2) if 3 == 4 else 4, 5  # works
```
