### ISSUE TITLE
verifyproblem creates data/sample/1.interaction.pstmp for interactive problems

### ISSUE THREAD

**Issue by simonlindholm** [Kattis/problemtools#136]

**Comment by thorehusfeldt** [comment]
My guess is that this happens here:

https://github.com/Kattis/problemtools/blob/063b68a98237773a11555c14fd2da07a25f68860/problemtools/templates/latex/problemset.cls#L375

As far as I know, LaTeX can’t remove files, at least not easily, so it would be somebody else’s responsibility to remove the temporary file in `data/sample/*.pstmp`.

I’m not sure what is a good place for that task. `problem2pdf.__exit__()` ?

**Comment by austrin** [comment]
My plan is to fix it by using a more standard latex tempfile name, something of the form `<name-of-main-tex-file>.<something>`.
