### ISSUE TITLE
time limit inclusion depends on current directory

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#16]
See [here](https://github.com/Kattis/problemtools/blob/master/src/ProblemPlasTeX/ProblemsetMacros.py#L39-L41)

This means if the problem set is in somepath/someid, the file somepath/someid/.timelimit is read iff the current working directory is 'somepath'. I wouldn't even know where to start to fix this.

**Comment by austrin** [comment]
Fixed in https://github.com/Kattis/problemtools/commit/8d5bb62172679bdbc834e36d5b80f0d091ca2d37
