### ISSUE TITLE
testdata group named `x.in` triggers 'missing x.ans' warning

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problemtools#169]
See title. The check for missing `.ans` files should probably check that the `.in` files are actually files and not directories.

**Comment by ghamerly** [comment]
While the code may technically be wrong here, it feels like it would cause more confusion than clarity to have test data directories that are named "x.in" or "y.ans".

**Comment by RagnarGrootKoerkamp** [comment]
I agree, but ran into this when adding testcases for BAPCtools.
What do you think is a reasonable stricter spec for testgroup names? Since currently the spec does allow this.
