### ISSUE TITLE
problemtools cannot be installed via pip into virtualenv

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#17]
Since not everyone runs Debian, and even if we run Debian, we may be force to use a virtualenv, it would be great if problemtools installed in a virtual environment.

Right now, this fails. Specifically, if I do:

```bash
mkdir v
virtualenv ./v
. ./v/bin/activate
pip install git+https://github.com/Kattis/problemtools.git
```
then I would expect a working problem tools in ./v.
However, it's missing, for instance, the HTML [templates](https://github.com/Kattis/problemtools/tree/master/templates). 

This leaves me to run problemtools from the git working directory, which in turn means it's harder to include problemtools's libraries in my own application. I'm insufficiently familiar with pip/setuptools to know how to fix this.

**Comment by austrin** [comment]
@godmar this should now (at long last) be working.
