### ISSUE TITLE
img base dir cannot be set in problem2html.py

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#18]
You have an option to set the imgbasedir, but you don't expose it.
See this [gist](https://gist.github.com/godmar/6ccb30916f1de9736f98) for what I mean.

**Comment by austrin** [comment]
@godmar that is true, but I'm not exactly sure if it would be useful to expose it.  Note that it does not change the names of the actual image files produced, it only affects what the links to them look like.  Would you have a use for it?
