### ISSUE TITLE
Should we require .ans files for interactive problems?

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problemtools#187]
Currently problemtools requires them, but they're usually ((almost) always?) not needed for interactive problems.

Should it just work without creating a bunch of empty .ans files?

**Comment by meisterT** [comment]
I believe we with would also need to change it in DOMjudge then.

**Comment by Tagl** [comment]
I believe this can be closed based on discussion here https://github.com/Kattis/problem-package-format/issues/98
Is that correct @RagnarGrootKoerkamp ?

**Comment by RagnarGrootKoerkamp** [comment]
Indeed this can be closed. Conclusion there: yes, `.ans` files must always exist.
