### ISSUE TITLE
Arch Linux (AUR) installation notes

### ISSUE THREAD

**Issue by arknave** [Kattis/problemtools#190]
My notes for installing on Arch Linux. I didn't use the AUR package (https://aur.archlinux.org/packages/kattis-problemtools/) because it wants to use python2. 

The only troublesome dependency is plastex, which is not in the official arch repositories. I installed it from the AUR using this PKGBUILD (https://aur.archlinux.org/packages/plastex/). After that, I made some small edits to the PKGBUILD (see my version here: https://gist.github.com/arknave/36b486b5bb9328e13d45e6a160e81652) and `makepkg -si` just worked :tada:

**Comment by thorehusfeldt** [comment]
@arknave : You may be confusing me with somebody else? I don’t know what the AUR PKGBUILD even is…

**Comment by arknave** [comment]
Sorry, I was trying to tag @t-wissmann and got auto-completed the wrong username.

**Comment by arknave** [comment]
Actually now I'm really confused who the right username is, apologies for all the tags. I'll make an AUR account and message the owner there.

**Comment by SvartaHjarta** [comment]
I've updated the [AUR package](https://aur.archlinux.org/packages/kattis-problemtools-git), feel free to ping me if there are any issues.

**Comment by t-wissmann** [comment]
Hi, thanks that you took care of it! I haven't been using kattis for a long time and so I marked the aur package as orphaned.

Sorry @arknave that I missed your ping :-(. I can't recall anymore what went wrong and why I didn't see you tagging me, but you were absolutely right :-)
