### ISSUE TITLE
cc -by-nc-sa license unsupported

### ISSUE THREAD

**Issue by godmar** [Kattis/problemtools#22]
Greater New York 2014 is published under [CC by-nc-sa](http://creativecommons.org/licenses/by-nc-sa/3.0/) but verifyproblem.py doesn't like it when I put in cc by-nc-sa as it's not a supported value.

So.... what does that mean?  Do you need one of the listed licenses for open kattis (you can't do with a NC clause because Kattis is a company?), or should I list 'educational' - which is sort of correct, or something else altogether?

**Comment by niemela** [comment]
The main reason that we did not include any CC nc licenses is that it's fairly unclear where problems under that license can actually be used. Using 'educational' would be wrong, that allows some uses that are not allowed under a CC nc. For the purpose of using this on Kattis the most correct thing would be to specifically ask the licensor for permission to do what we want to do and the use the "license" 'permission'.

A better solution for situations like this would be if we could allow multiple licenses for problems, and then mark these as 'CC by-nc-sa' as well as 'permission'. That is not currently supported, and I'm not sure if it would be worth the added complication.

Thoughts?

**Comment by godmar** [comment]
One suggestion may be to have a short blurb/web page with an exact description of "what we want to do" - I'm guessing that's inclusion in a Kattis-hosted contest, and future hosting on open.kattis.com, correct?  Basically, some prepared text so that a copyright holder could say: "Yes, I'm giving you permission to do that." 

Case in point for GNY 2014: I haven't asked for permission yet, I'd assumed them publishing the problems under CC by-nc-sa was good enough.

**Comment by niemela** [comment]
That's a good idea.

For now though, what we (for we = Kattis) want is permission to:
1. Use the problems for one of the NA ICPC training contests
2. Use the problems on the Kattis online judge (https://open.kattis.com)
3. Use the problems on educational sites such as https://uchicago.kattis.com or https://webster.kattis.com.
