### ISSUE TITLE
MacOS Support - ERROR in input format validators: No input format validators found

### ISSUE THREAD

**Issue by osalbahr** [Kattis/problemtools#225]
# Error

I am having issues with verifyproblem in problemtools/icpc. Specifically, it can't find my input format validators.

```
root@2d6ba22ff932:/# verifyproblem crosswords/
Loading problem crosswords
Checking config
Checking statement
Checking validators
ERROR in input format validators: No input format validators found
Checking graders
Checking data
Checking submissions
   AC submission scrabble.cpp (C++) OK: AC [CPU: 0.01s @ test case sample/1]
   Slowest AC runtime: 0.005, setting timelim to 1 secs, safety margin to 2 secs
crosswords tested: 1 error, 0 warnings
root@2d6ba22ff932:/# echo $?
1
root@2d6ba22ff932:/# ls crosswords/input_validators/
Makefile  validator.cpp
root@2d6ba22ff932:/# 
```

The same issue does not happen if I boot an Ubuntu Live USB into the same laptop. Is problemtools/icpc supported on MacOS? I'm not sure why the host OS would cause issues, since that is what Docker is for. Here is how I run it:

```
docker run --rm -it -v $PWD/crosswords/:/crosswords problemtools/icpc
```

# System Information
```
$ neofetch
...
OS: macOS 12.6.3 21G419 x86_64
...
```

**Comment by simonlindholm** [comment]
Does it work if you rename input_validators -> input_format_validators (the old name)?

**Comment by osalbahr** [comment]
> Does it work if you rename input_validators -> input_format_validators (the old name)?

Yes. Does that mean `problemtools/icpc` is outdated?

```
root@7544e0ae1895:/# verifyproblem crosswords 
Loading problem crosswords
Checking config
Checking statement
Checking validators
Checking graders
Checking data
Checking submissions
   AC submission scrabble.cpp (C++) OK: AC [CPU: 0.00s @ test case secret/8]
   Slowest AC runtime: 0.005, setting timelim to 1 secs, safety margin to 2 secs
crosswords tested: 0 errors, 0 warnings
root@7544e0ae1895:/# 
```

The same happens with `problemtools/full`:

```
root@477f11cbbcc8:/# verifyproblem crosswords/
Loading problem crosswords
Checking config
Checking statement
Checking validators
Checking graders
Checking data
Checking submissions
   AC submission scrabble.cpp (C++) OK: AC [CPU: 0.03s @ test case sample/2]
   Slowest AC runtime: 0.030, setting timelim to 1 secs, safety margin to 2 secs
crosswords tested: 0 errors, 0 warnings
root@477f11cbbcc8:/# 
```

**Comment by simonlindholm** [comment]
Yep, definitely sounds like it!

**Comment by osalbahr** [comment]
It looks like it was last updated [3 years ago](https://hub.docker.com/r/problemtools/).

Not sure if there are plans to maintain it and keep it updated. If so, I’d be happy to help with that. Either ways, I think at least a note under Method 2 is probably needed as a warning. At first, it seemed to me as if it was the most reliable method. Maybe it was in the beginning. For now, using Method 1 on Ubuntu seems to work fine so I will continue with that.

**Comment by austrin** [comment]
Docker images are updated now so this is no longer relevant as far as I can tell.
