### ISSUE TITLE
pip3 system-wide option installs in $HOME/.local/bin

### ISSUE THREAD

**Issue by osalbahr** [Kattis/problemtools#227]
I installed the required `apt` packages in the README (and `python3-pip`) then ran `pip3 install git+https://github.com/kattis/problemtools`. And for some reason, pip still prompted me to add `$HOME/.local/bin` to my `$PATH`. as that is where pip installed the tools.

Is this an issue with my setup? Or is it a recent change to `pip3`'s (default) behavior?

<img width="864" alt="Screen Shot 2023-03-27 at 9 41 40 PM" src="https://user-images.githubusercontent.com/54853250/228104838-1a6c7926-9e18-4a9e-97f2-962b314677e5.png">

**Comment by simonlindholm** [comment]
This is expected unless you run pip with sudo -- it detects that you don't have root permissions and automatically behaves as if you passed --user. I think pip has done this for the last couple of years at least.

**Comment by osalbahr** [comment]
Thank you for clarifying. Should that be part of the README?

**Comment by simonlindholm** [comment]
Yeah, the command for system-wise installation should probably have a sudo in front of it. Or be removed altogether, because there's little good reason to use it.

**Comment by austrin** [comment]
Fixed in README.md.
