### ISSUE TITLE
verifiy problem not working

### ISSUE THREAD

**Issue by EinarDarri** [Kattis/problemtools#254]
![image](https://github.com/Kattis/problemtools/assets/54663445/53d91767-c2fe-492b-b4b4-b8c7736c6ab1)

I just installed problemtools and it seams that the latest merge #253  added an error

this error is showing up on all problems that I try to verify

**Comment by incaseoftrouble** [comment]
Hi, this is my fault, I merged something and forgot to check. You can use #256 until it is merged

**Comment by gkreitz** [comment]
#256 is merged, closing.
