### ISSUE TITLE
verifyproblem.py crashes on symlink to checker run script

### ISSUE THREAD

**Issue by eldering** [Kattis/problemtools#27]
I've created a checker in a subdirectory. It uses checktestdata as a library, so it's not a simple file that can be compiled. Instead the build file does 'make checker' and 'run' is a symlink to that binary 'checker'. Note that 'checker' need not exist yet before the build script is executed; I wanted to see whether that was accepted. Instead verifyproblem.py crashed, see the output below.

$ ../../../problemtools/src/verifyproblem.py .
Loading problem <removed>
Traceback (most recent call last):
  File "../../../problemtools/src/verifyproblem.py", line 1085, in <module>
    with Problem(args.problemdir) as prob:
  File "../../../problemtools/src/verifyproblem.py", line 1005, in __enter__
    self.output_validators = OutputValidators(self)
  File "../../../problemtools/src/verifyproblem.py", line 769, in __init__
    self._validators = get_programs(os.path.join(problem.probdir, 'output_validators'), problem.tmpdir, error_handler=self)
  File "../../../problemtools/src/verifyproblem.py", line 38, in get_programs
    ret.append(Program(path, tmpdir, includedir=includedir))
  File "/home/jaap/contest-jury/problemtools/src/program.py", line 284, in __init__
    self.add_files(path)
  File "/home/jaap/contest-jury/problemtools/src/program.py", line 271, in add_files
    shutil.copy(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/jaap/<removed>/run'

**Comment by austrin** [comment]
Right, symlinks have their contents copied rather than being copied as symlinks.  And that behaviour is convenient occasionally because it means you can easily share code between solutions, validators, etc, without having to duplicate it, so I would be inclined to keep that behaviour (since there are easy workarounds for the use case you describe).  But even so, it should of course be handled more graciously than crashing.

**Comment by eldering** [comment]
Ok, fair enough on that default behaviour.

Actually a better solution to my problem (and I think something we brought up on standards discussions) is to make it not a requirement that a run script be present until after the build script has been executed.

**Comment by austrin** [comment]
@eldering fixed:
1. Symlinks to non-existent files do not result in a crash but an error message.
2. Run script does not have to exist until after build script has been run.
