### ISSUE TITLE
problempart parsing is too greedy

### ISSUE THREAD

**Issue by meisterT** [Kattis/problemtools#28]
`../../problemtools/src/verifyproblem.py -p data .`

fails with
`verifyproblem.py: error: argument -p/--parts: Invalid problem part specified: .`

because `.` is consumed by the argument parser instead of leaving it as positional argument for the directory name.

**Comment by austrin** [comment]
That is how pythons argparser works.  You can either use `--` to signify end of the `-p` list, or put the `-p` part at the end (i.e. `verifyproblem.py -p data -- .`, or `verifyproblem.py . -p data`).

**Comment by meisterT** [comment]
Ok, thanks.
