### ISSUE TITLE
Better support of .timelimit file

### ISSUE THREAD

**Issue by austrin** [Kattis/problemtools#34]
If a problem has a .timelimit file, then verifyproblem should use the time limit stated there if it is within reasonable margin of the calculated (non-rounded) time limit (e.g. if it is within 10% or something like that?).

If it deviates by more, a warning should be issued, I guess.

.timelimit should maybe also be written by verifyproblem?

**Comment by austrin** [comment]
As part of doing this, remember to check that the .timelimit is an integer since other parts of problemtools won't work with a non-integer limit.

**Comment by niemela** [comment]
I would argue that this is not needed after https://github.com/Kattis/problem-package-format/pull/49
