### ISSUE TITLE
Input validation -- strict syntax checking

### ISSUE THREAD

**Issue by ghamerly** [Kattis/problemtools#71]
The input validation checker already warns if the input validator accepts things like the empty file, binary file, etc (https://github.com/Kattis/problemtools/blob/develop/problemtools/verifyproblem.py#L693).

When I am reviewing a problem for someone else I check for good input validators. I find that people often use inadequate syntax checking (e.g. their input validators check ranges on numbers, but not that each line is properly formatted with regular expressions). It's tedious for me to check for this and then explain why strict syntax checking is a good thing&trade;.

Here's an idea on how to automate this checking. Suppose we have verifyproblem play with the spacing of some input files that are in the problem already and pass validation. That is, add extra spaces and/or newlines where they already exist. If there is already an input format validator that uses strict syntax checking with regular expressions, then for many (most?) types of problems those input files should fail validation. If they don't then verifyproblem could give a warning.

If this is considered worthwhile, I can work on the changes.

**Comment by xiaoyuansuo51** [comment]
I think this is such a great idea.

**Comment by austrin** [comment]
@ghamerly yes, would be great, I've been thinking about adding something like that.  In addition to the checks you mention, another basic check would be to add some random trailing junk to an input file.
