### ISSUE TITLE
Minimum score and maximum score should be allowed to be equal

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problemtools#74]
This is for example what you want for the sample group.

Current behaviour for `range: 0 0`:
```ERROR in test case group data/sample: Invalid score range '0 0': minimum score must be smaller than maximum score```

Expected behaviour:
no errors

**Comment by austrin** [comment]
I'm not sure I understand.  Why would you want a scoring problem where all scores are the same?  Isn't that just a pass-fail problem and should be defined as such?

**Comment by jsannemo** [comment]
Ranges can be defined per subtask, and for e.g. sample subtasks you generally want `range: 0 0`.
