### ISSUE TITLE
Don't warn about duplicate test cases in different test groups

### ISSUE THREAD

**Issue by simonlindholm** [Kattis/problemtools#78]

**Comment by austrin** [comment]
Alas I think this is a wontfix, at least as written.  One of the most common uses of the warning is to warn about sample cases being duplicated in secret.

I guess one could imagine some form of "don't warn about duplicate test cases in different test groups that are judged in different ways".  Or maybe simply command line flags to disable certain classes of warnings (including this one) for problems where they are not relevant?

**Comment by simonlindholm** [comment]
If we accept #80 I agree that this should be wontfix.

**Comment by simonlindholm** [comment]
Oh, and to respond to the rest of it: I do agree that we oughtn't warn about duplicated cases with different output validators, but that seems like a more minor bugfix than anything else, and it wouldn't reduce our pain any. A flag is about as bad as just telling people to ignore the messages, but a problem.yaml setting could be viable if we don't accept #80.

**Comment by simonlindholm** [comment]
Closing since #80 was merged.
