### ISSUE TITLE
Clean install on Ubuntu 18.04 failing with make builddeb

### ISSUE THREAD

**Issue by FinnLidbetter** [Kattis/problemtools#79]
I'm having trouble installing the problemtools. I am working from Ubuntu 18.04 and after installing only git and the listed build dependencies in debian/control I get the following error: `/usr/lib/python2.7/dist-packages/setuptools/dist.py:406: UserWarning: The version specified ('v1.20170420-15-ga52bdb2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.`

Complete output on the command `make builddeb` is as follows.

finn@finn-VirtualBox:~/problemtools$ make builddeb
dpkg-buildpackage -us -uc -tc -b
dpkg-buildpackage: info: source package kattis-problemtools
dpkg-buildpackage: info: source version 1.20180426
dpkg-buildpackage: info: source distribution artful
dpkg-buildpackage: info: source changed by Per Austrin <austrin@kattis.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build problemtools
 fakeroot debian/rules clean
make[1]: Entering directory '/home/finn/problemtools'
dh clean --with python2 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
   dh_clean -O--buildsystem=pybuild
make[1]: Leaving directory '/home/finn/problemtools'
 debian/rules build
make[1]: Entering directory '/home/finn/problemtools'
dh build --with python2 --buildsystem=pybuild
   dh_update_autotools_config -O--buildsystem=pybuild
   dh_auto_configure -O--buildsystem=pybuild
I: pybuild base:217: python2.7 setup.py config 
/usr/lib/python2.7/dist-packages/setuptools/dist.py:406: UserWarning: The version specified ('v1.20170420-15-ga52bdb2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running config
   dh_auto_build -O--buildsystem=pybuild
I: pybuild base:217: /usr/bin/python setup.py build 
/usr/lib/python2.7/dist-packages/setuptools/dist.py:406: UserWarning: The version specified ('v1.20170420-15-ga52bdb2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build
running build_support
Running command: make -C support install DESTDIR=/home/finn/problemtools/.pybuild/cpython2_2.7/build/problemtools/support
make[2]: Entering directory '/home/finn/problemtools/support'
git submodule update --init
Submodule 'checktestdata' (https://github.com/DOMjudge/checktestdata) registered for path 'checktestdata'
Cloning into '/home/finn/problemtools/support/checktestdata'...
fatal: unable to access 'https://github.com/DOMjudge/checktestdata/': Failed to connect to 127.0.0.1 port 9: Connection refused
fatal: clone of 'https://github.com/DOMjudge/checktestdata' into submodule path '/home/finn/problemtools/support/checktestdata' failed
Failed to clone 'support/checktestdata'. Retry scheduled
Cloning into '/home/finn/problemtools/support/checktestdata'...
fatal: unable to access 'https://github.com/DOMjudge/checktestdata/': Failed to connect to 127.0.0.1 port 9: Connection refused
fatal: clone of 'https://github.com/DOMjudge/checktestdata' into submodule path '/home/finn/problemtools/support/checktestdata' failed
Failed to clone 'support/checktestdata' a second time, aborting
Makefile:19: recipe for target 'checktestdata/bootstrap' failed
make[2]: *** [checktestdata/bootstrap] Error 1
make[2]: Leaving directory '/home/finn/problemtools/support'
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    'build': build
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 44, in run
    self.run_command('build_support')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 29, in run
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', 'support', 'install', 'DESTDIR=/home/finn/problemtools/.pybuild/cpython2_2.7/build/problemtools/support']' returned non-zero exit status 2
E: pybuild pybuild:336: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 
dh_auto_build: pybuild --build -i python{version} -p 2.7 returned exit code 13
debian/rules:14: recipe for target 'build' failed
make[1]: *** [build] Error 25
make[1]: Leaving directory '/home/finn/problemtools'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
Makefile:5: recipe for target 'builddeb' failed
make: *** [builddeb] Error 2

**Comment by FinnLidbetter** [comment]
Looking through the closed issues I found that
`git submodule update --init --recursive` fixed the problem for me as in #11 
Was the make updated correctly to fetch this submodule as was stated when #11 was closed?

**Comment by eightants** [comment]
Old issue, but I ran into the same problem on my Ubuntu installation today with the same fix needed.

**Comment by mikaelgoldmann** [comment]
I think #171 would fix this.
