### ISSUE TITLE
don't use -i with html tidy

### ISSUE THREAD

**Issue by ghamerly** [Kattis/problemtools#89]
HTML tidy with the `-i` option can introduce unwanted newlines and spaces inside of `<pre>` blocks.  This can cause problem2html to produce sample data that looks incorrect (has leading spaces, e.g.).

Here's a minimal example that gets messed up by `tidy -i`:

```
<!DOCTYPE html>
<html><head><title>test</title></head><body>
<pre>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</pre>
</body>
</html>
```
Running `tidy -i` on this input produces:
```
<!DOCTYPE html>
<html>
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Linux version 5.2.0">
  <title>test</title>
</head>
<body>
  <pre>
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</pre>
</body>
</html>
```
If you remove one of the "a" characters, then the problem disappears (the `<pre>` remains on one line).

The problem seems to occur when the pre input is too long.

I read a bit online -- it looks like this behavior is a known "feature" of HTML tidy. See this example which does exactly what we do not want -- adding a newline to the beginning of a `<pre>` section:
http://www.html-tidy.org/documentation/#featured-options-and-solutions
So... I think the "best" fix is just to remove `-i` from when we invoke tidy.

**Comment by ghamerly** [comment]
An alternative (identified by @niemela) is that version 5.6 and above of HTML tidy seem to fix the problem.

**Comment by niemela** [comment]
@ghamerly Was this fixed back in 2019?

**Comment by JoelNiemela** [comment]
This seems to be fixed. The version of tidy in Ubuntu 20.04 (which is what is used in the problemtools Dockerfile) is tidy 5.6.

**Comment by ghamerly** [comment]
Agreed, closing.
