### ISSUE TITLE
A seg-faulting solution hangs verifyproblem.py

### ISSUE THREAD

**Issue by lukipuki** [Kattis/problemtools#9]
Download http://www.csc.kth.se/~polacek/stol.zip, unzip it and run problemtools on the package. The TLE solution will hang on test case 11:
```
Running stol.cpp on test case secret/stol.11...
```
Changing MAXN from 400 to 1000 makes the solution time out. The one with 400 seg-faults:
```
[1]    822 segmentation fault  ./stol.cpp.bin < ../../data/secret/stol.11.in
```

It seems that a seg-faulting solution in the TLE directory makes verifyproblem.py hang.

**Comment by austrin** [comment]
The solution in question does not segfault but hangs on walltime.  Enforcing a walltime limit should be added to problemtools, at some point, but this issue as written is invalid.
